# Generated by Django 4.2.7 on 2023-12-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_id',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
