# Generated by Django 4.2.7 on 2023-12-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartify', '0003_alter_appointment_date_alter_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(),
        ),
    ]
