# Generated by Django 4.2.7 on 2023-12-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartify', '0004_alter_appointment_date_alter_appointment_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
