# Generated by Django 4.2.7 on 2023-12-17 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heartify', '0006_doctor_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='field',
            new_name='specialisation',
        ),
    ]
