# Generated by Django 4.2.7 on 2023-12-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartify', '0007_rename_field_doctor_specialisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='problem_description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=5000),
        ),
    ]
