# Generated by Django 4.2.7 on 2023-12-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartify', '0008_alter_appointment_problem_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('chest_pain_type', models.CharField(max_length=20)),
                ('resting_bp', models.IntegerField()),
                ('cholesterol', models.IntegerField()),
                ('fasting_bs', models.CharField(max_length=5)),
                ('resting_ecg', models.CharField(max_length=20)),
                ('max_hr', models.IntegerField()),
                ('exercise_angina', models.CharField(max_length=5)),
                ('oldpeak', models.FloatField()),
                ('st_slope', models.CharField(max_length=10)),
                ('result', models.IntegerField()),
            ],
        ),
    ]
