# Generated by Django 4.2.7 on 2023-12-28 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heartify', '0012_alter_selftestresult_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='selftestresult',
            options={},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.RemoveField(
            model_name='selftestresult',
            name='email',
        ),
        migrations.RemoveField(
            model_name='selftestresult',
            name='name',
        ),
        migrations.RemoveField(
            model_name='selftestresult',
            name='result',
        ),
        migrations.AddField(
            model_name='appointment',
            name='person_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='heartify.personprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='person_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='heartify.personprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selftestresult',
            name='person_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='selftest_results', to='heartify.personprofile'),
            preserve_default=False,
        ),
    ]
