# Generated by Django 4.2.7 on 2023-12-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartify', '0017_alter_personprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='selftestresult',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
