# Generated by Django 4.2.7 on 2023-12-28 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heartify', '0018_alter_appointment_email_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selftestresult',
            options={'verbose_name': 'Self Tests', 'verbose_name_plural': 'Self Tests'},
        ),
    ]
