# Generated by Django 4.2.7 on 2023-12-28 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heartify', '0019_alter_selftestresult_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.RemoveField(
            model_name='selftestresult',
            name='email',
        ),
        migrations.RemoveField(
            model_name='selftestresult',
            name='name',
        ),
    ]
