# Generated by Django 4.2.7 on 2023-12-29 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heartify', '0021_doctor_age_doctor_email_doctor_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personprofile',
            options={'verbose_name': 'UserProfile', 'verbose_name_plural': 'UserProfiles'},
        ),
        migrations.AlterModelOptions(
            name='selftestresult',
            options={'verbose_name': 'SelfTest', 'verbose_name_plural': 'SelfTests'},
        ),
    ]
